const eula =
  `<h2> Nutanix End User License Agreement (EULA) and Terms of Use </h2>
    <p class='eula'>IMPORTANT — READ CAREFULLY
      READ THIS END USER LICENSE AGREEMENT (THE “AGREEMENT”) BEFORE DOWNLOADING, INSTALLING, COPYING, CONFIGURING, ACCESSING, DEPLOYING, USING THE SOFTWARE AND/OR USING NUTANIX SUPPORT. BY DOWNLOADING, INSTALLING, COPYING, CONFIGURING, ACCESSING, DEPLOYING, USING NUTANIX SUPPORT AND/OR OTHERWISE USING ALL OR ANY PART OF THE SOFTWARE OR BY CLICKING ON AN “ACCEPT” BUTTON, YOU AGREE TO THE TERMS AND CONDITIONS OF THIS AGREEMENT. YOU FURTHER AGREE THAT YOU ARE BOUND BY AND ARE A PARTY TO THIS AGREEMENT, AND, IF YOU ARE ACCEPTING THESE TERMS ON BEHALF OF ANOTHER PERSON OR A COMPANY OR OTHER LEGAL ENTITY, YOU REPRESENT AND WARRANT THAT YOU HAVE FULL AUTHORITY TO BIND THAT PERSON, COMPANY, OR LEGAL ENTITY TO THESE TERMS.
      YOUR USE OF THE SOFTWARE IS EXPRESSLY CONDITIONED ON YOUR ACCEPTANCE OF THE TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE TO THE TERMS AND CONDITIONS OF THIS AGREEMENT:
      DO NOT ORDER OR PURCHASE THE SOFTWARE
      DO NOT DOWNLOAD, INSTALL, COPY, CONFIGURE, ACCESS, DEPLOY, CLICK ON AN “ACCEPT” BUTTON, USE NUTANIX SUPPORT AND/OR OTHERWISE USE THE SOFTWARE
      DELETE THE UNUSED SOFTWARE AND RETURN THE UNUSED SOFTWARE TO THE VENDOR FROM WHICH YOU ACQUIRED IT
      This Agreement is between You, on behalf of the company, partnership or business entity that You represent (“You” or “Your”) and either (a) Nutanix, Inc. a Delaware corporation, with offices located at 1740 Technology Drive, Suite 150, San Jose, CA 95110, USA if the Software was purchased in the Americas; or (b) Nutanix Netherlands, B.V. incorporated and registered in The Netherlands with its registered office at Scorpius 100, 2132 LR Hoofddorp, The Netherlands, if the Software was purchased in any other country ((a) and (b) are referred to herein as “Nutanix”).
      “Authorized Nutanix System” means either (i) a device that runs the Software and is branded as a Nutanix device; or (ii) a device that runs the Software and is branded with a third party’s brand pursuant to an original equipment manufacturing agreement between Nutanix and the third party; or (iii) a device (including its specific configuration) that has been authorized in writing by Nutanix to run the Software.
      “Documentation” means Nutanix’s published user and administration manuals and other documentation for the Software that is furnished to You.
      “License Period” means, unless otherwise stated on the Entitlement, the life of the Authorized Nutanix System upon which the Software is initially installed.
      “Licensed Unit” means the unit of measure by which Your use of Software is licensed, as described in Your Entitlement.
      “Purchased Software” means Software that has been purchased by You for a separate license fee.
      “Software” means any Nutanix software, Purchased Software, library, utility, tool or other computer or program code, in object (binary) or source-code form provided, directly or indirectly to You, including without limitation firmware. The term “Software” also includes any Updates, Upgrades or other new features, functionality or enhancements to the Software made available directly or indirectly to You by Nutanix.
      “Support Guide” means the Nutanix Worldwide Support Program Guide (located at http://go.nutanix.com/rs/nutanix/images/nutanix-support-guide.pdf) which may be updated from time to time by Nutanix.
      “Update” means either a Minor Release, a Maintenance Release or a Patch Release as those terms are defined in the Support Guide.
      “Upgrade” means a Major Release as that term is defined in the Support Guide.
      This Agreement applies to all Software and Documentation made available by Nutanix to You.
      License Grant and Entitlement. The Software and Documentation are licensed, not sold, to You by Nutanix. This Agreement confers no title or ownership and is not a sale of any rights in the Software. Subject to the terms and conditions of this Agreement, the terms of Your entitlement which evidences Your authorization to use the Software and the authorized scope of use of the Software (“Entitlement”), and payment of the purchase price and/or all fees, You are hereby granted a limited, revocable, non-assignable, non-exclusive, non-sublicensable and non-transferable right to run one copy of the object code version of the Software on one Authorized Nutanix System during the License Period, for internal business operations only (“Permitted Use”). The Entitlement shall be specified in writing on the order acknowledgement or equivalent document issued by Nutanix or the party from whom You have lawfully acquired the products. The Entitlement shall specify the name of the product, the number of Licensed Unit(s) and the usage level, version and/or feature set authorized. Your Permitted Use is limited to the number of Licensed Unit(s) stated in Your Entitlement.  Use of the Software outside the scope of Your Entitlement is unauthorized and shall constitute a material breach of this Agreement and void the warranty and/or support obligations of which You may otherwise be entitled. You agree to use Your best efforts to prevent and protect the contents of the Software and Documentation from unauthorized disclosure or use. Nutanix and its licensors reserve all rights, including but not limited to ownership and intellectual property rights, not expressly granted to You. Nutanix’s licensors are the intended third party beneficiaries of this Agreement and have the express right to rely upon and directly enforce the terms set forth herein. There are no implied licenses granted by Nutanix under this Agreement. Except as expressly specified above, You shall have no rights to the Software.
      Use.
      2.1 Limitations on Use. You must not use the Software or Documentation except as permitted by this Agreement. You must not:
      alter, decompile, disassemble, modify, unbundle or create any derivative works of the Software, the underlying source code, or the Documentation in any way, including without limitation customization, translation or localization;
      port, emulate the functionality, reverse compile, reverse assemble, reverse engineer, create derivative works, or otherwise reduce to human readable form or attempt to separate any of the components of the Software or derive the source code for the Software;
      copy, redistribute, encumber, sell, rent, lease, license, sublicense, or otherwise transfer rights to the Software or Documentation, use the Software for the benefit of any third party or on a hosted basis;
      remove or alter any trademark, logo, copyright or other proprietary notices, legends, symbols or labels in the Software or Documentation or any product in which the Software is embedded;
      disclose the results of testing, benchmarking or other performance or evaluation information related to the Software or the product to any third party without the prior written consent of Nutanix;
      access or use the Software or Documentation for any competitive purposes (e.g. to gain competitive intelligence; to design or build a competitive product or service, or a product providing features, functions or graphics similar to those used or provided by Nutanix; to copy any features, functions or graphics; or to monitor availability, performance or functionality for competitive purposes);
      use any “locked” or key restricted feature, function or capability without first purchasing the applicable license and obtaining a valid key, even if such feature, function or capability is enabled without a key; or
      distribute any copy of the Software to any third party, including as may be embedded in equipment sold in the secondhand market;
      unless specifically permitted in writing in an Entitlement, transfer the Software from an Authorized Nutanix System to another Authorized Nutanix System or to another device.
      You must not cause, encourage or permit any third party to do any of the foregoing.
      If You believe that any of the foregoing restrictions are prohibited by local law, You agree to provide Nutanix with at least ninety (90) days advance written notice of Your belief and provide all reasonably requested information from Nutanix to evaluate Your claim. Nutanix may, in its discretion, impose reasonable conditions, including a reasonable fee, on such use of the Software, or offer to provide alternatives to ensure that Nutanix’s proprietary rights in the Software are protected and to reduce any adverse impact on Nutanix’s proprietary rights.
      2.2. Third Party Software. You acknowledge that the Software may contain copyrighted software of third parties which are obtained under a license from such parties (“Third Party Software”). All third party licensors retain all right, title and interest in and to such Third Party Software and all copies thereof, including all copyright and other intellectual property rights. Your use of any Third Party Software shall be subject to, and You shall comply with, the terms and conditions of this Agreement, and the applicable restrictions and other terms and conditions set forth in any Third Party Software documentation or printed materials, including without limitation an end user license agreement.
      Open Source Components. Software may use or include one or more of the open source software components listed in the Nutanix open source attribution file, which is available at www.nutanix.com/opensource. Please refer to the open source attribution file for the open source license disclosures and pertinent terms.
      Proprietary Rights. You acknowledge and agree that the Software belongs to Nutanix or its licensors. You agree that You neither own nor hereby acquire any claim or right of ownership to the Software and Documentation or to any related patents, copyrights, trademarks or other intellectual property, including all modifications and derivative works of any of the foregoing. Nutanix and its licensors retain all right, title and interest both tangible and intangible in and to all copies of the Documentation and the Software at all times, regardless of the form or media in or on which the original or other copies may subsequently exist. This license is not a sale of the original or any subsequent copy. The Software and Documentation are protected by copyright and other intellectual property laws and by international treaties. Any and all other copies of the Software or Documentation made by You are in violation of this license. All content accessed through the Software is the property of the applicable content owner and may be protected by applicable copyright law. This license gives You no rights to such content. All trademarks used in connection with the Software and Documentation are owned by Nutanix, its affiliates and/or its licensors and other suppliers, and no license to use any such trademarks is provided hereunder. All suggestions or feedback provided by You to Nutanix with respect to the Software shall be Nutanix’s property and deemed Confidential Information of Nutanix. You hereby assign to Nutanix all right, title and interest in and to any feedback provided to Nutanix.
      Support. Nutanix’s support obligations for the Software, if any, are delineated in a separate agreement. If You have purchased Support, the terms governing such support may be found at http://www.nutanix.com/support/support-terms. Nutanix does not provide any product maintenance or support services under this Agreement. This Agreement does not entitle You to any Updates or Upgrades at any time in the future.
      Term and Termination. This Agreement and Your right to use the Software and Documentation may be terminated by You at any time upon written notice. This Agreement automatically terminates if (a) You or any of Your employees or consultants fail to comply with its terms and conditions; or (b) You terminate or suspend Your business, become insolvent, admit in writing Your ability to pay Your debts as they mature, make an assignment for the benefit of creditors or become subject to any bankruptcy or insolvency proceeding. Upon expiration or termination of this Agreement for any reason: (a) all licenses granted by Nutanix shall immediately terminate; (b) You shall immediately discontinue use of the applicable Software and products; (c) You shall destroy all copies of the Software and Documentation in Your possession, custody or control; and (d) if requested, You shall certify to Nutanix in writing that such return or destruction has occurred. The preamble as well as Sections 2, 4, 6, 7, 8, 10, 12, 14, 15 and 16 shall survive any expiration or termination of this Agreement.
      Warranty.
      7.1 Nutanix warrants to You that the Purchased Software will substantially conform to the specifications in the Documentation for the ninety (90) day period from (i) the date of shipment of the Authorized Nutanix System to You or (ii) the date Nutanix first makes the initial version or release of the Purchased Software available to You, whichever is earlier. Nutanix does not warrant that the operation of the Purchased Software will be uninterrupted or error free, or that all defects can or will be corrected.
      7.2 Nutanix’s entire liability, and Your exclusive remedy, under this warranty will be for Nutanix, at Nutanix’s option: (i) to use reasonable efforts to remedy the defective Purchased Software within a reasonable period of time so as to cause it to operate as warranted; (ii) to replace the affected Purchased Software; or (iii) if, after reasonable efforts Nutanix is not able to correct the deficiencies, to accept return of the affected Purchased Software for a refund of the amount paid by You for the affected Purchased Software and the pre‐paid and unused portion of any remaining term of Support for the affected Purchased Software.
      7.3 EXCEPT AS PROVIDED IN SECTION 7.1 ABOVE, YOU AGREE THAT THE SOFTWARE AND DOCUMENTATION ARE PROVIDED “AS IS” AND THAT NUTANIX AND ITS LICENSORS MAKE NO OTHER WARRANTIES AS TO THE SOFTWARE OR DOCUMENTATION, INCLUDING WITHOUT LIMITATION UNINTERRUPTED USE, ACCURACY, AND DATA LOSS. NUTANIX AND ITS LICENSORS DISCLAIM ALL OTHER WARRANTIES, EXPRESS OR IMPLIED, WRITTEN OR ORAL, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE (EVEN IF NUTANIX KNOWS OR SHOULD HAVE KNOWN OF SUCH PURPOSE), AND ANY WARRANTIES ARISING BY STATUTE, OPERATION OF LAW, COURSE OF DEALING OR PERFORMANCE, OR USAGE OF TRADE, OR THAT THE SOFTWARE WILL BE COMPATIBLE OR WORK WITH ANY THIRD PARTY SOFTWARE OR HARDWARE OR ANY OTHER NUTANIX PRODUCTS INCLUDING OTHER AUTHORIZED NUTANIX SYSTEMS. NUTANIX AND ITS LICENSORS DO NOT WARRANT THAT THE SOFTWARE OR DOCUMENTATION OR ANY RESULTS OF USE THEREOF WILL BE FREE OF DEFECTS, ERRORS OR VIRUSES, RELIABLE OR ABLE TO OPERATE ON AN UNINTERRUPTED BASIS OR IN A PARTICULAR ENVIRONMENT OR THAT ERRORS THEREIN, IF ANY, WILL BE CORRECTED. YOU FURTHER ACKNOWLEDGE THAT THE SOFTWARE IS NOT INTENDED OR SUITABLE FOR USE IN SITUATIONS OR ENVIRONMENTS WHERE THE FAILURE OR TIME DELAYS OF, OR ERRORS OR INACCURANCIES IN THE CONTENT, DATA OR INFORMATION PROVIDED BY THE NUTANIX SOFTWARE COULD LEAD TO DEATH, PERSONAL INJURY, OR SEVERE PHYSICAL OR ENVIRONMENTAL DAMAGE.
      LIMITATION OF LIABILITY. TO THE FULLEST EXTENT PERMITTED BY LAW, NUTANIX AND ITS LICENSORS SHALL NOT BE LIABLE FOR ANY DAMAGES, WHETHER IN CONTRACT OR TORT (INCLUDING NEGLIGENCE) OR ANY OTHER LEGAL OR EQUITABLE THEORY, ARISING FROM THIS AGREEMENT, INCLUDING WITHOUT LIMITATION ANY INDIRECT, CONSEQUENTIAL, SPECIAL, EXEMPLARY, INCIDENTAL DAMAGES, EVEN IF NUTANIX HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES OR FOR ANY LOST REVENUES, GOODWILL OR PROFITS, BUSINESS INTERRUPTION, PROCUREMENT OF SUBSTITUTE HARDWARE, SOFTWARE OR SERVICES, LOST DATA, WORK STOPPAGE, RE-RUN TIME, INACCURATE OUTPUT, COMPUTER FAILURE OR MALFUNCTION. YOU AGREE THAT YOU SHALL HAVE THE SOLE RESPONSIBILITY FOR PROTECTING YOUR DATA, BY PERIODIC BACKUP OR OTHERWISE. IN ANY CASE, NUTANIX’S SOLE LIABILITY AND YOUR EXCLUSIVE REMEDY UNDER ANY PROVISION OF THIS AGREEMENT SHALL BE THE REPLACEMENT OF THE SOFTWARE FOUND TO BE DEFECTIVE, WITH THE EXCEPTION OF DEATH OR PERSONAL INJURY CAUSED BY THE NEGLIGENCE OF NUTANIX TO THE EXTENT APPLICABLE LAW PROHIBITS THE LIMITATION OF DAMAGES IN SUCH CASES. NUTANIX SHALL NOT BE LIABLE FOR ANY CLAIM BROUGHT MORE THAN ONE YEAR AFTER THE CAUSE OF ACTION FOR SUCH CLAIM FIRST AROSE. BECAUSE SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OR LIABLITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, THE PRECEDING LIMITATIONS MAY NOT APPLY TO YOU IN WHICH CASE NUTANIX’S LIABILITY UNDER THIS AGREEMENT WILL NOT EXCEED THE AMOUNT OF THE LICENSE FEES YOU PAID FOR THE SOFTWARE GIVING RISE TO THE CLAIM.
      Infringement. Subject to the remainder of this section, Nutanix shall defend or settle, at its own expense, any third-party action against You to the extent based upon a claim that the Purchased Software infringes any copyright or trademark or misappropriates any trade secret (a “Claim”), and will pay such damages or costs as are finally awarded against You attributable to such Claim, provided that You (i) notify Nutanix promptly in writing of any such Claim, (ii) give Nutanix sole control of the defense and/or settlement of such Claim (iii) give Nutanix all reasonable information and assistance, and (iv) are not in material breach of this Agreement. Should the Purchased Software become, or in the opinion of Nutanix be likely to become, the subject of such an infringement Claim, Nutanix may replace or modify, in whole or in part, the Purchased Software to make it non-infringing. Nutanix assumes no liability hereunder for: (a) any method or process in which the Purchased Software may be used; (b) its compliance with Your specifically requested specifications; (c) use of Purchased Software other than a current unaltered release of the Purchased Software or use of any older version of the Purchased Software when the use of a newer release of the Purchased Software made available to You would have avoided the infringement; (d) the combination, operation or use of the Purchased Software with non-Nutanix products or services; or (e) use of the Purchased Software in a manner or for a purpose for which it was not intended. You shall indemnify and hold harmless Nutanix and its officers, directors, employees, agents, successors and assigns against any damages, losses, and expenses (including reasonable attorneys’ fees) arising from any third-party action to the extent based upon a claim that the Purchased Software infringes any copyright or trademark or misappropriates any trade secret due to any of the foregoing factors, and shall give Nutanix all reasonable information and assistance regarding such claim. THIS SECTION 9 SETS FORTH NUTANIX’S ENTIRE LIABILITY AND OBLIGATION AND YOUR SOLE REMEDY FOR ANY CLAIMS OR ACTIONS RELATED TO INFRINGEMENT OF ANY INTELLECTUAL PROPERTY RIGHTS.
      Confidentiality. "Confidential Information" shall mean the Software and Documentation and all other information disclosed to You that Nutanix characterizes as confidential at the time of its disclosure either in writing or orally, except for information which You can demonstrate: (a) is previously rightfully known to You without restriction on disclosure; (b) is or becomes, from no act or failure to act on Your part, generally known in the relevant industry or public domain; (c) is disclosed to You by a third party as a matter of right and without restriction on disclosure; or (d) is independently developed by You without access to the Confidential Information. You shall use Your best efforts to preserve and protect the confidentiality of the Confidential Information at all times. You shall not disclose, disseminate or otherwise publish or communicate Confidential Information to any person, firm, corporation or other third party without the prior written consent of Nutanix. You shall not use any Confidential Information other than in the course of the activities permitted hereunder. You shall notify Nutanix in writing immediately upon discovery of any unauthorized use or disclosure of Confidential Information or any other breach of this Agreement, and will cooperate with Nutanix in every reasonable way to regain possession of Confidential Information and prevent any further unauthorized use. If You are legally compelled to disclose any of the Confidential Information, then, prior to such disclosure, You will (i) immediately notify Nutanix prior to such disclosure to allow Nutanix an opportunity to contest the disclosure, (ii) assert the privileged and confidential nature of the Confidential Information, and (iii) cooperate fully with Nutanix in protecting against any such disclosure and/or obtaining a protective order narrowing the scope of such disclosure and/or use of the Confidential Information. In the event such protection is not obtained, You shall disclose the Confidential Information only to the extent necessary to comply with the applicable legal requirements. The foregoing obligations shall survive any termination or expiration of this Agreement.
      Technical Information. You agree that Nutanix may collect or process technical and related information arising from Your use of the Software which may include but may not be limited to internet protocol address, hardware identification, operating system, application software, peripheral hardware, and non-personally identifiable Software usage statistics to facilitate the provisioning of Updates, Support, invoicing or online services.
      Injunctive Relief. You acknowledge and agree that Your breach or threatened breach of this Agreement shall cause Nutanix irreparable damage for which recovery of money damages would be inadequate and that Nutanix therefore may obtain timely injunctive relief to protect its rights under this Agreement in addition to any and all other remedies available at law or in equity.
      Compliance with Laws; Export Control. Each Party shall comply with all laws applicable to the actions contemplated by this Agreement.  You acknowledge that the Software is of United States origin, and is subject to the U.S. Export Administration Regulations, and may be subject to the export control laws of the applicable territory, and that diversion contrary to applicable export control laws is prohibited.  You represent that (1) You are not, and are not acting on behalf of, (a) any person who is a citizen, national, or resident of, or who is controlled by the government of any country to which the United States has prohibited export transactions; or (b) any person or entity listed on the U.S. Treasury Department lists of Specially Designated Nationals, Foreign Sanctions Evaders, Sectoral Sanctions Identifications, or Palestinian Legislative Council; or the U.S. Commerce Department Denied Persons List, Entity List, or Unverified List; or the U.S. State Department Nonproliferation Sanctions, or Debarred List; and (2) You will not permit the Software, directly, or indirectly, to be used for any purposes prohibited by law, including any prohibited development, design, manufacture or production of missiles or nuclear, chemical or biological weapons.  The Software and Documentation are deemed to be “commercial computer software” and “commercial computer software documentation”, respectively, pursuant to DFARS Section 227.7202 and FAR Section 12.212(b), as applicable.  Any use, modification, reproduction, release, performing, displaying or disclosing of Software and Documentation by or for the U.S. Government shall be governed solely by the terms and conditions of this Agreement. You agree that the Software may not be exported/re-exported to Cuba, Iran, North Korea, Sudan and Syria. Furthermore, You agree not to resell, transfer, or re-export products without prior authorization from Nutanix or the U.S. government to any military entity of: Albania, Armenia, Azerbaijan, Belarus, Cambodia, China (PRC), Georgia, Iraq, Kazakhstan, Kyrgyzstan, Laos, Macau, Moldova, Mongolian P.R., Russia, Tajikistan, Turkmenistan, Uzbekistan, Ukraine, Vietnam.
      Governing Law. To the extent permitted by applicable law, this Agreement is governed by and construed in accordance with the substantive laws of either: (a) the State of California, U.S.A. if You first took delivery of the Software in the United States, Mexico or Canada and You expressly and irrevocably agree and submit to the exclusive jurisdiction of the federal and state courts located in Santa Clara County, California, U.S.A.; or (b) England, if You first took delivery of the Software outside of the United States, Mexico or Canada, and You expressly and irrevocably agree and submit to the exclusive jurisdiction of the English courts. This Agreement will not be governed by the conflict of laws rules of any jurisdiction or the U.N. Convention on Contracts for the International Sale of Goods, the application of which is expressly excluded.
      Miscellaneous. If any part of this Agreement is held invalid or unenforceable, that part shall be construed to reflect the parties’ original intent, and the remaining portions remain in full force and effect. The controlling language of this Agreement is English. If You have received a translation into another language, it has been provided for Your convenience only. A waiver by either party of any term or condition of this Agreement or any breach thereof, in any one instance, shall not waive such term or condition or any subsequent breach thereof. You may not assign, delegate any performance, or otherwise transfer by operation of law or otherwise this Agreement or any rights or obligations herein. You agree not to copy, sell, give or assign the Software or any part thereof to a third party. Nutanix may assign this Agreement to any person or entity at its sole discretion. You represent and warrant that the performance of any activities contemplated by this Agreement do not and shall not conflict with any other agreement or obligation to which You are a party or by which You are bound. This Agreement shall be binding upon and shall inure to the benefit of the Parties, their successors and permitted assigns. This Agreement constitutes the entire and sole agreement between You and Nutanix with respect to the Software and Documentation and supersedes all prior and contemporaneous agreements relating to the Software and Documentation, whether oral or written (including any inconsistent terms contained in a purchase order). If You are found to have breached Section 2 or Section 10 of this Agreement, then Nutanix shall be awarded attorney fees, costs and expenses. This Agreement may be amended only in writing signed by authorized representatives of both Parties and specifically referring to this provision. This Agreement will be interpreted without being construed for or against either Party. The words “includes” and “including” and the abbreviation “e.g.” will be deemed to be followed by the words “without limitation”.
      User Outside the U.S. If You are using the Software or Documentation outside the U.S., then the following shall apply: (a) You confirm that this Agreement and all related documentation is and will be in the English language; (b) You are responsible for complying with any local laws in Your jurisdiction which might impact Your right to import, export or use the Software and Documentation, and You represent that You have complied with any regulations or registration procedures required by applicable law to make this license enforceable. </p>

    <p class='agreed fw'>
      <input type="checkbox" style='margin-right:10px;'>
      I have read and agree to terms and conditions
    </p>

    <div class="signature fw">
      <input type="text" placeholder="Name">
      <input type="text" placeholder="Company">
      <input type="text" placeholder="Email">
    </div>
    <hr>

    <div class='two-col fw btns'>
      <button class='secondary'>Cancel</button>
      <button class='primary accept'>  Accept</button>
    </div>
  `
